pr: none

trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - message-board/liquibase

jobs:
- job: Build
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:

  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      repository: jakepelter/message-board-liquibase
      dockerfile: message-board/liquibase/Dockerfile
      tags: |
        $(Build.BuildId)
        
  - task: Docker@2
    displayName: Push
    inputs:
      command: push
      repository: jakepelter/message-board-liquibase
      containerRegistry: 'jakep-dockerhub'
      tags: |
        $(Build.BuildId)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: message-board/liquibase/charts
      artifactName: 'drop'