# NOTICE THE SEPARATOR ---
# APPLY EACH MANIFEST IN ORDER
apiVersion: v1
kind: Namespace
metadata:
  name: message-board
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "kubernetes.azure.com/scalesetpriority", "Operator": "Equal", "Value": "spot", "Effect": "NoSchedule"}]'
# THE ABOVE TOLERATION LETS PODS FROM THIS NAMESPACE BE SCHEDULED ON SPOT NODES IN AZURE!
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
  namespace: message-board
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: devops
  namespace: message-board
  annotations:
    kubernetes.io/service-account.name: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-rb
  namespace: message-board
subjects:
- kind: ServiceAccount
  name: devops
  namespace: message-board
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io