apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: jakep-dockerhub
      containers:
      - name: {{ .Release.Name }}
        image: docker.io/jakepelter/message-board-python-flask:{{ .Values.imageTag }}
        ports:
        - containerPort: 5000
        env:
        - name: SQL_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: playbook-message-board-db
              key: USER
        - name: SQL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: playbook-message-board-db
              key: PASS
        - name: SQL_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: playbook-message-board-db
              key: HOST
        - name: SQL_SERVER_DB
          valueFrom:
            secretKeyRef:
              name: playbook-message-board-db
              key: DB
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: {{ .Release.Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/limit-rpm: "15"
spec:
  tls:
  - hosts:
    - discuss.pelter.net
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: discuss.pelter.net
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 5000